apiVersion: v1
kind: PersistentVolumeClaim # выделяет место на диске для бд в случае, если она упадет
metadata:
  name: influxdb-volume
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector: #к чему прикрепляется 
    app: influxdb
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - name: influxdb-port
      protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1 #до версии 1.9.0 нужно использовать apps/v1beta2
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1 #запускает 1 под, созданный по шаблону
  strategy:
    type: Recreate #завершит работу всех запущенных экземпляров, а затем воссоздает их с более новой версией
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb-image
        imagePullPolicy: Never #image is not pulling from DockerHub        
        ports:
        - containerPort: 8086