apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: mysql-pv
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector: #к чему прикрепляется 
    app: mysql
  type: ClusterIP
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1 #до версии 1.9.0 нужно использовать apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1 #запускает 1 под, созданный по шаблону
  strategy:
    type: Recreate #завершит работу всех запущенных экземпляров, а затем воссоздает их с более новой версией
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-image
        imagePullPolicy: Never #image is not pulling from DockerHub        
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-pv
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc