apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector: #к чему прикрепляется 
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 80 
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh  
      protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 #запускает 1 под, созданный по шаблону
  strategy:
    type: Recreate #завершит работу всех запущенных экземпляров, а затем воссоздает их с более новой версией
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never #image is not pulling from DockerHub        
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22