#This specification creates a new Service object named "my-service", which targets TCP port 9376 on any Pod with the app=MyApp label
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector: #к чему прикрепляется 
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
    - protocol: TCP
      port: 443
      targetPort: 443
#    - protocol: TCP
#      port: 22 #снутри
#      targetPort: 22 #внутри

---
apiVersion: apps/v1 # до версии 1.9.0 нужно использовать apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # запускает 1 под, созданный по шаблону
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never #image is not pulling from DockerHub        
        ports:
        - containerPort: 80