#This specification creates a new Service object named "my-service", which targets TCP port 9376 on any Pod with the app=MyApp label
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector: #к чему прикрепляется 
    app: nginx
  type: LoadBalancer
#  externalIPs:
#  - 192.168.0.10
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 80 
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh  
      protocol: TCP
      port: 22
      targetPort: 22

---
apiVersion: apps/v1 # до версии 1.9.0 нужно использовать apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # запускает 1 под, созданный по шаблону
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never #image is not pulling from DockerHub        
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22