
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - name: phpmyadmin-port
      protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin #поле .spec.selector определяет, как Deployment находит, какими модулями нужно управлять
  #A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value"
  replicas: 1
  strategy: 
    type: Recreate #завершит работу всех запущенных экземпляров, а затем воссоздает их с более новой версией
  template: #шаблон
    metadata:
      labels:
        app: phpmyadmin 
    spec:
      containers: #indicates that the Pods run one container
        - name: phpmyadmin
          image: phpmyadmin-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000