apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector: #к чему прикрепляется 
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - name: ftps-port
      protocol: TCP
      port: 21
      targetPort: 21
    # - name: ftps-port
    #   protocol: TCP
    #   port: 21
    #   targetPort: 21
---
apiVersion: apps/v1 #до версии 1.9.0 нужно использовать apps/v1beta2
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1 #запускает 1 под, созданный по шаблону
  strategy:
    type: Recreate #завершит работу всех запущенных экземпляров, а затем воссоздает их с более новой версией
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never #image is not pulling from DockerHub        
        ports:
        - containerPort: 3000